---
apiVersion: terraform.appvia.io/v1alpha1
kind: Configuration
metadata:
  name: s3-bucket
  namespace: apps
spec:
  module: https://github.com/appvia/terraform-aws-bucket?ref=master

  providerRef:
    name: aws

  valueFrom:
    - context: default
      key: eks_oidc_issuer_arn
      name: eks_issuer_arn
    - context: default
      key: eks_name
      name: cluster_name

  variables:
    bucket_name: my-test-s3-bucket
    configuration: s3-bucket
    namespace: apps
    service_account_name: default
